import React from 'react';

const AboutPage: React.FC = () => {
  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Privacy Policy</h3>
          <p className="card-description">Win5x Privacy Policy and Data Protection</p>
        </div>
        <div className="card-content space-y-6 text-gray-300">
          <div>
            <p className="mb-4">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Interpretation and Definitions</h4>
            <h5 className="text-md font-medium text-white mb-2">Interpretation</h5>
            <p className="mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions.
              The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Definitions</h4>
            <p className="mb-3">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Company</strong> refers to win5x, also referred to as "the Company", "We", "Us" or "Our" in this Agreement.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            </ul>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Collecting and Using Your Personal Data</h4>
            <h5 className="text-md font-medium text-white mb-2">Types of Data Collected</h5>
            
            <div className="mb-4">
              <h6 className="text-sm font-medium text-white mb-2">Personal Data</h6>
              <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
              </ul>
            </div>

            <div className="mb-4">
              <h6 className="text-sm font-medium text-white mb-2">Usage Data</h6>
              <p className="mb-2">Usage Data is collected automatically when using the Service. Usage Data may include information such as:</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Your Device's Internet Protocol address (e.g. IP address)</li>
                <li>Browser type and version</li>
                <li>The pages of our Service that You visit</li>
                <li>The time and date of Your visit</li>
                <li>Time spent on those pages</li>
                <li>Unique device identifiers and other diagnostic data</li>
              </ul>
            </div>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Tracking Technologies and Cookies</h4>
            <p className="mb-3">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
            <p className="mb-3">The technologies We use may include:</p>
            <ul className="list-disc list-inside ml-4 space-y-2">
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
              <li><strong>Flash Cookies.</strong> Our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</li>
            </ul>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Use of Your Personal Data</h4>
            <p className="mb-3">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc list-inside ml-4 space-y-2">
              <li>To provide and maintain our Service, including to monitor the usage of our Service</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service</li>
              <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased</li>
              <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication</li>
              <li>To provide You with news, special offers and general information about other goods, services and events that we offer</li>
              <li>To manage Your requests: To attend and manage Your requests to Us</li>
              <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets</li>
              <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service</li>
            </ul>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Security of Your Personal Data</h4>
            <p className="mb-3">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Children's Privacy</h4>
            <p className="mb-3">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Changes to this Privacy Policy</h4>
            <p className="mb-3">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
            </p>
          </div>

          <div>
            <h4 className="text-lg font-semibold text-white mb-3">Contact Us</h4>
            <p className="mb-3">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p>By email: <a href="mailto:winein5x@gmail.com" className="text-blue-400 hover:text-blue-300 underline">winein5x@gmail.com</a></p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;


